/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.baquiax.idepascal.ventanas;



import com.baquiax.idepascal.utiles.ManejoArchivo;
import com.baquiax.idepascal.utiles.NumberLine;
import com.baquiax.idepascal.utiles.Utiles;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.StringReader;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 * @author Luis
 */
public class Editor extends javax.swing.JFrame {

    private NumberLine numberLine;
    private Utiles utiles;

    private ManejoArchivo archivo;
    private List<String> rutas;
    private String ruta;

    //graphviz 
    private String content;
    private String dot;
    private String img;

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        setLocationRelativeTo(null);

        this.utiles = new Utiles();
        this.archivo = new ManejoArchivo();
        this.rutas = new ArrayList<>();
        this.ruta = "";
        rutas.add("");

        this.content = "";
        this.dot = "";
        this.img = ManejoArchivo.IMG_TREE;
      

        //simbols

        setLineNumbers();
        setIconMenu();

    }

    private void setLineNumbers() {
        numberLine = new NumberLine(editor);
        scrollEditor.setRowHeaderView(numberLine);
    }

    private void setIconMenu() {
        utiles.setIcon(menunewFile, "/img/new1.png");
        utiles.setIcon(menuOpen, "/img/open.png");
        utiles.setIcon(menuSave, "/img/save.png");
        utiles.setIcon(menuEjecutar, "/img/run.png");
        utiles.setIcon(menuReportes, "/img/report.png");
        utiles.setIcon(menuCloseFile, "/img/salir.png");
        utiles.setIcon(menuSimbols, "/img/simbol.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrollEditor = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menunewFile = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuCloseFile = new javax.swing.JMenuItem();
        menuEjecutar = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        menuLexico = new javax.swing.JMenuItem();
        menuSintactico = new javax.swing.JMenuItem();
        menuSemantico = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSimbols = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(420);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        editor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scrollEditor.setViewportView(editor);

        jTabbedPane1.addTab("Pestaña", scrollEditor);

        jSplitPane1.setTopComponent(jTabbedPane1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consola"));

        consola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(consola);

        jSplitPane1.setRightComponent(jScrollPane1);

        jMenuBar1.setBorder(null);
        jMenuBar1.setAlignmentY(1.5F);

        menu.setText("Archivo");

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpen.setText("Abrir archivo");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        menu.add(menuOpen);

        menunewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menunewFile.setText("Nuevo archivo");
        menunewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewFileActionPerformed(evt);
            }
        });
        menu.add(menunewFile);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSave.setText("Guardar archivo");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menu.add(menuSave);

        menuCloseFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCloseFile.setText("Cerrar archivo");
        menuCloseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseFileActionPerformed(evt);
            }
        });
        menu.add(menuCloseFile);

        jMenuBar1.add(menu);

        menuEjecutar.setText("Ejecutar");
        menuEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEjecutarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuEjecutarMouseExited(evt);
            }
        });
        menuEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEjecutarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuEjecutar);

        menuReportes.setText("Reporte de errores");

        menuLexico.setText("Errores lexicos");
        menuLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLexicoActionPerformed(evt);
            }
        });
        menuReportes.add(menuLexico);

        menuSintactico.setText("Errores sintácticos");
        menuSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSintacticoActionPerformed(evt);
            }
        });
        menuReportes.add(menuSintactico);

        menuSemantico.setText("Errores semánticos");
        menuSemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSemanticoActionPerformed(evt);
            }
        });
        menuReportes.add(menuSemantico);

        jMenuItem1.setText("Ver todos los errores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem1);

        jMenuBar1.add(menuReportes);

        menuSimbols.setText("Tabla de símbolos");
        menuSimbols.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSimbolsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSimbols);

        jMenu3.setText("Ayuda...");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menunewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewFileActionPerformed
        // TODO add your handling code here:
        ruta = "";
        abrirNuevaPestaña();
        rutas.add("");
    }//GEN-LAST:event_menunewFileActionPerformed

    private void abrirNuevaPestaña() {

        JTextPane pane = new JTextPane();
        Font font = editor.getFont().deriveFont(editor.getFont().getSize());
        pane.setFont(font);
        JScrollPane scrollPane = new JScrollPane(pane);

        NumberLine line = new NumberLine(pane);

        scrollPane.setRowHeaderView(line);

        jTabbedPane1.addTab("Nueva pestaña", scrollPane);
        jTabbedPane1.setSelectedComponent(scrollPane);
    }

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
        if (jTabbedPane1.getComponents().length > 0) {
            guardarArchivo();
        }
    }//GEN-LAST:event_menuSaveActionPerformed

    private void guardarArchivo() {

        int index = jTabbedPane1.getSelectedIndex();
        JScrollPane scrooll = (JScrollPane) jTabbedPane1.getSelectedComponent();
        JTextPane edicion = (JTextPane) scrooll.getViewport().getView();

        if (!rutas.get(index).equals("")) {
            archivo.writeFile(rutas.get(index), edicion.getText());
        } else {
            ruta = archivo.saveFile();
            if (!ruta.equals("")) {
                File file = new File(ruta + ManejoArchivo.FILTRO);
                jTabbedPane1.setTitleAt(index, file.getName());
                rutas.set(index, ruta + ManejoArchivo.FILTRO);
                archivo.writeFile(ruta + ManejoArchivo.FILTRO, edicion.getText());
            }
        }
    }

    private void menuCloseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseFileActionPerformed
        // TODO add your handling code here:
        System.out.println("cerrando");
        if (jTabbedPane1.getSelectedComponent() != null) {
            System.out.println(jTabbedPane1.getSelectedIndex());
            //if (jTabbedPane1.getSelectedIndex() > 0) {

            rutas.remove(jTabbedPane1.getSelectedIndex());
            jTabbedPane1.remove(jTabbedPane1.getSelectedIndex());

            //}
        }
    }//GEN-LAST:event_menuCloseFileActionPerformed

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        // TODO add your handling code here:
        System.out.println("nuevo archivo");
        ruta = archivo.openFile();
        if (jTabbedPane1.getComponents().length > 0) {
            if (!ruta.equals("")) {
                JScrollPane scrooll = (JScrollPane) jTabbedPane1.getSelectedComponent();
                JTextPane edicion = (JTextPane) scrooll.getViewport().getView();

                edicion.setText(archivo.readFile(ruta));

                File file = new File(ruta);
                int index = jTabbedPane1.getSelectedIndex();
                jTabbedPane1.setTitleAt(index, file.getName());
                rutas.set(index, file.getAbsolutePath());
            }
        }

    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEjecutarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuEjecutarActionPerformed

    private void menuEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEjecutarMouseClicked
        // TODO add your handling code here:
 
        if (jTabbedPane1.getComponents().length > 0) {
            JScrollPane scrooll = (JScrollPane) jTabbedPane1.getSelectedComponent();
            JTextPane edicion = (JTextPane) scrooll.getViewport().getView();
            consola.setText("");
            System.out.println("ejecutando...");
            if (!edicion.getText().isBlank()) {
                // System.out.println(edicion.getText());

                
            } else {
                consola.setForeground(Color.red);
                consola.setText("Nada que ejecutar");
            }
        }
    }//GEN-LAST:event_menuEjecutarMouseClicked

    private void menuLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLexicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLexicoActionPerformed

    private void menuSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSintacticoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSintacticoActionPerformed

    private void menuSemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSemanticoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSemanticoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuEjecutarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEjecutarMouseExited
        // TODO add your handling code here:
        menuEjecutar.setRequestFocusEnabled(false);
    }//GEN-LAST:event_menuEjecutarMouseExited

    private void menuSimbolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSimbolsMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuSimbolsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane consola;
    private javax.swing.JTextPane editor;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuCloseFile;
    private javax.swing.JMenu menuEjecutar;
    private javax.swing.JMenuItem menuLexico;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSemantico;
    private javax.swing.JMenu menuSimbols;
    private javax.swing.JMenuItem menuSintactico;
    private javax.swing.JMenuItem menunewFile;
    private javax.swing.JScrollPane scrollEditor;
    // End of variables declaration//GEN-END:variables
}
