
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 10 19:21:11 CST 2024
//----------------------------------------------------

package com.baquiax.idepascal.backend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 72;
  public static final int DIVISION = 46;
  public static final int REAL = 29;
  public static final int MENOR_IGUAL = 64;
  public static final int PACKED = 25;
  public static final int TYPE = 35;
  public static final int CONST = 7;
  public static final int COR_C = 56;
  public static final int COR_A = 55;
  public static final int UNTIL = 36;
  public static final int MAYOR = 62;
  public static final int DIFERENTE = 61;
  public static final int INTEGER = 41;
  public static final int PAR_C = 54;
  public static final int FALSE = 77;
  public static final int PAR_A = 53;
  public static final int NOT = 22;
  public static final int ARRAY = 3;
  public static final int MULTI = 45;
  public static final int VAR = 37;
  public static final int THEN = 33;
  public static final int GOTO = 17;
  public static final int DOS_PUNTOS = 52;
  public static final int RECORD = 28;
  public static final int LLAVE_C = 59;
  public static final int LLAVE_A = 58;
  public static final int PUNTO_COMA = 49;
  public static final int UNARIO = 69;
  public static final int MOD = 21;
  public static final int OR_ELSE = 71;
  public static final int COMA = 48;
  public static final int ENTERO = 73;
  public static final int TKCHAR = 8;
  public static final int TRUE = 76;
  public static final int IGUAL = 47;
  public static final int WHILE = 38;
  public static final int DECIMAL = 74;
  public static final int BOOLEAN = 68;
  public static final int AND_THEN = 70;
  public static final int LONGINT = 66;
  public static final int DO = 11;
  public static final int FOR = 42;
  public static final int DIV = 10;
  public static final int DOWNTO = 12;
  public static final int READLN = 31;
  public static final int ELSE = 13;
  public static final int MENOS = 43;
  public static final int MENOR = 63;
  public static final int BREAK = 5;
  public static final int PROCEDURE = 26;
  public static final int EOF = 0;
  public static final int PUNTO = 50;
  public static final int SUMA = 44;
  public static final int FUNCTION = 16;
  public static final int REPEAT = 30;
  public static final int LABEL = 20;
  public static final int IN = 19;
  public static final int COMILLA = 60;
  public static final int OR = 24;
  public static final int SET = 32;
  public static final int error = 1;
  public static final int WRITELN = 40;
  public static final int TRES_PUNTO = 51;
  public static final int CONTINUE = 9;
  public static final int IF = 18;
  public static final int IGUALACION = 57;
  public static final int OF = 23;
  public static final int END = 14;
  public static final int FILE = 15;
  public static final int BEGIN = 4;
  public static final int CASE = 6;
  public static final int CADENA = 75;
  public static final int STRING = 67;
  public static final int PROGRAM = 27;
  public static final int AND = 2;
  public static final int TO = 34;
  public static final int WITH = 39;
  public static final int MAYOR_IGUAL = 65;
}

